name: Wake Render Services

on:
  schedule:
    - cron: '33-59/10 6 * * 1-5'
  workflow_dispatch:

jobs:
  wake:
    runs-on: ubuntu-latest
    steps:
      - name: Wake Render App 1
        run: |
          curl -I https://kzz-select.onrender.com

      - name: Wake Render App 2
        run: |
          curl -I https://bdmster-new.onrender.com
